#!/usr/bin/env python

from optparse import OptionParser
import fileinput, sys, re
import hashlib
import os

HELP_MSG = '''
Given any text file or stdin input, this program will scan it for any
<code...></code> tags with 'lang="..."' attributes.  When it finds any it will
replace it with xhtml that looks exactly like whatever it looks like in your
locally installed gvim.  Whatever is in the 'lang' tag attribute is used as the
filetype.

It stores code snippets in a ./.tmp_vctr_cache directory so that if you are
running it in short iterations it won't have to regenerate every single snippet
(which can take long when launching gvim on some platforms).  It requires gvim
(although you can possibly get it to work with vim).

Reads from stdin if no file specified. Output goes to stdout. If multiple files
are specified they still go to stdout (effectively concatenating them).  Pulls
it all into memory right now because I'm lazy.'''


CODE_RE = r'<code[^>]*?(?:lang="(?P<lang>[^"]*))[^>]*>(?P<cont>.*?)</code>'
CACHE_D = '.tmp_vctr_cache'

comp_check =       False
force_render_all = False
save_to_cache =    True

def calculate_id(lang, cont):
    m = hashlib.md5()
    m.update(lang + cont)
    return str(len(cont)) + '_' + m.hexdigest()

def render_code(language, content):
    return 'uh.. rendered?'

def get_rendered(language, content):
    global comp_check
    global force_render_all
    global save_to_cache
    id = calculate_id(language, content)
    cache_loc = os.path.join(CACHE_D, id)
    if not force_render_all and not comp_check and os.path.exists(cache_loc):
        print '<1>',
        rendered = render_code(language, content)
        existing = open(cache_loc, 'r').read()
        comp_check = True
        force_render_all = rendered != existing
        return rendered
    if not force_render_all and os.path.exists(cache_loc):
        print '<2>',
        return open(cache_loc, 'r').read()
    rendered = render_code(language, content)
    if save_to_cache:
        open(cache_loc,'w+').write(rendered)
    print '<3>',
    return rendered

def parse_data(dat):
    re_cb = re.compile(CODE_RE, re.S | re.I)
    for block in re_cb.finditer(dat):
        rendered = get_rendered(block.group('lang'), block.group('cont'))
        dat = dat.replace(block.group(), rendered)
    sys.stdout.write(dat)

def main():
    global comp_check
    global force_render_all
    global save_to_cache
    oparser = OptionParser(usage='Usage: %prog [options] [INPUT-FILE]', description=HELP_MSG)
    # TODO: option for forcing (ignore cache) and for not doing a cache check
    options, args = oparser.parse_args()

    if not os.path.exists(CACHE_D):
        force_render_all = True
        os.mkdir(CACHE_D)

    dat = ''
    for d in fileinput.input(args):
        dat += d
    parse_data(dat)

if __name__ == '__main__':
    main()
